---

- hosts: kubeadm
  tasks:
   - name: stop running deployment
     shell: kubectl delete deploy first
     ignore_errors: yes
   - name: stop running service
     shell: kubectl delete svc devopsjenk
     ignore_errors: yes
   - name: start service
     shell: kubectl create -f service.yaml
   - name: start deployment
     shell: kubectl create -f deployment.yaml
